// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEFGeLP9aPN-tkehOYofqrwOZsuvBzgE',
    appId: '1:863023058422:web:352f3efe4ae9d1c6568bd7',
    messagingSenderId: '863023058422',
    projectId: 'nutriscan-c087d',
    authDomain: 'nutriscan-c087d.firebaseapp.com',
    storageBucket: 'nutriscan-c087d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2xbvSa24ex72V_kny6lH2mg8z7573Vt8',
    appId: '1:863023058422:android:1ab062c49d5b1e61568bd7',
    messagingSenderId: '863023058422',
    projectId: 'nutriscan-c087d',
    storageBucket: 'nutriscan-c087d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKV4Y_BMTAKRZNG1fduJN1O4xLo2bXfZw',
    appId: '1:863023058422:ios:ee3487e6b57d7d8f568bd7',
    messagingSenderId: '863023058422',
    projectId: 'nutriscan-c087d',
    storageBucket: 'nutriscan-c087d.appspot.com',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKV4Y_BMTAKRZNG1fduJN1O4xLo2bXfZw',
    appId: '1:863023058422:ios:ee3487e6b57d7d8f568bd7',
    messagingSenderId: '863023058422',
    projectId: 'nutriscan-c087d',
    storageBucket: 'nutriscan-c087d.appspot.com',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuEFGeLP9aPN-tkehOYofqrwOZsuvBzgE',
    appId: '1:863023058422:web:ed0c5e5266ce945a568bd7',
    messagingSenderId: '863023058422',
    projectId: 'nutriscan-c087d',
    authDomain: 'nutriscan-c087d.firebaseapp.com',
    storageBucket: 'nutriscan-c087d.appspot.com',
  );
}
